from __future__ import annotations

from typing import Any, Protocol


class ApiService(Protocol):
    def handle_request(self, payload: dict[str, Any]) -> dict[str, Any]: ...


class ChatApiService(Protocol):
    def start_session(self, complaint_text: str) -> dict[str, Any]: ...
    def continue_session(self, session_id: str, user_response: str) -> dict[str, Any]: ...
    def get_state(self, session_id: str) -> dict[str, Any]: ...
    def get_evidence_pack(self, session_id: str) -> dict[str, Any]: ...
